version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events_test
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
